-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 18:49:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Expediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Expediente` (
  `idExpediente` INT NOT NULL,
  `Rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idExpediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `cod_Administrador` VARCHAR(45) NULL,
  `Rol` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Expediente_idExpediente` INT NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  INDEX `fk_Administrador_Expediente1_idx` (`Expediente_idExpediente` ASC) VISIBLE,
  UNIQUE INDEX `cod_Administrador_UNIQUE` (`cod_Administrador` ASC) VISIBLE,
  CONSTRAINT `fk_Administrador_Expediente1`
    FOREIGN KEY (`Expediente_idExpediente`)
    REFERENCES `mydb`.`Expediente` (`idExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trabajador` (
  `idTrabajador` INT NOT NULL,
  `Codigo` VARCHAR(45) NULL,
  `Rol_trabajador` VARCHAR(45) NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idTrabajador`),
  INDEX `fk_Trabajador_Administrador1_idx` (`Administrador_idAdministrador` ASC) VISIBLE,
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Trabajador_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `mydb`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa_legal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa_legal` (
  `idEmpresa_legal` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `RUC` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Codigo` VARCHAR(45) NULL,
  `Trabajador_idTrabajador` INT NOT NULL,
  PRIMARY KEY (`idEmpresa_legal`, `Trabajador_idTrabajador`),
  INDEX `fk_Empresa_legal_Trabajador1_idx` (`Trabajador_idTrabajador` ASC) VISIBLE,
  UNIQUE INDEX `RUC_UNIQUE` (`RUC` ASC) VISIBLE,
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Empresa_legal_Trabajador1`
    FOREIGN KEY (`Trabajador_idTrabajador`)
    REFERENCES `mydb`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gestor_de_expedientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gestor_de_expedientes` (
  `idGestor` INT NOT NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  `Expediente_idExpediente` INT NOT NULL,
  PRIMARY KEY (`idGestor`),
  INDEX `fk_Gestor_de_expedientes_Administrador1_idx` (`Administrador_idAdministrador` ASC) VISIBLE,
  INDEX `fk_Gestor_de_expedientes_Expediente1_idx` (`Expediente_idExpediente` ASC) VISIBLE,
  CONSTRAINT `fk_Gestor_de_expedientes_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `mydb`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gestor_de_expedientes_Expediente1`
    FOREIGN KEY (`Expediente_idExpediente`)
    REFERENCES `mydb`.`Expediente` (`idExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Expediente_has_Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Expediente_has_Trabajador` (
  `Expediente_idExpediente` INT NOT NULL,
  `Trabajador_idTrabajador` INT NOT NULL,
  PRIMARY KEY (`Expediente_idExpediente`, `Trabajador_idTrabajador`),
  INDEX `fk_Expediente_has_Trabajador_Trabajador1_idx` (`Trabajador_idTrabajador` ASC) VISIBLE,
  INDEX `fk_Expediente_has_Trabajador_Expediente_idx` (`Expediente_idExpediente` ASC) VISIBLE,
  CONSTRAINT `fk_Expediente_has_Trabajador_Expediente`
    FOREIGN KEY (`Expediente_idExpediente`)
    REFERENCES `mydb`.`Expediente` (`idExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Expediente_has_Trabajador_Trabajador1`
    FOREIGN KEY (`Trabajador_idTrabajador`)
    REFERENCES `mydb`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
